### ISSUE TITLE
[New game]: Knife Hit Game 

### ISSUE THREAD

**Issue by Yashgabani845** [ChromeGaming/GameSphere#1026]
### 🎮 Game Request

**Description:**
Knife Hit Master is an addictive and challenging arcade game where players must throw knives to hit targets while avoiding hitting other knives already stuck in the targets. The game tests your precision, timing, and nerves as you progress through various levels of difficulty.

**Gameplay:**
1. **Objective:** The objective of the game is to throw knives and hit the targets without hitting any other knives already stuck in them.
  
2. **Rules:**
    - Tap the screen to throw a knife.
    - Each level consists of a rotating log or target with knives stuck into it.
    - You must hit the target a certain number of times to progress to the next level.
    - If you hit an existing knife, it's game over.
  
3. **Points:**
    - Earn points for each successful hit on the target.
  
4. **Loss:**
    - You lose a life if you hit another knife or miss the target completely.
    - The game ends when all lives are lost.
  
5. **Win:**
    - Progress through levels by successfully hitting the target the required number of times.
    - Win the game by completing all levels.

6. **Levels:**
    - The game consists of multiple levels with increasing difficulty.
    - Each level introduces new challenges such as faster rotating targets, moving obstacles, or smaller targets.
    - Unlock new knives and backgrounds as you advance through the levels.

### Point down the features

Game points
- Technologies : HTML , CSS , JS
- Knife and rotationg circle as assets
- points and no of knife at levels
-differnt anmation for each level

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

**Comment by sakship2005** [comment]
Hi! I would like to work on this game.
