### ISSUE TITLE
[New game]: Coil Game

### ISSUE THREAD

**Issue by Anjaliavv51** [ChromeGaming/GameSphere#1039]
### 🎮 Game Request

Game logic and basic description

Coil is an addictive HTML5 game where you have to defeat your enemies by enclosing them in your trail. Most of the game is drawn on 2d canvas but if WebGL support is detected additional effects are added.

### Point down the features

Game points

coil the blue to get points except Red and Yellow.

Game Preview

https://github.com/ChromeGaming/GameSphere/assets/154777864/5f318234-9799-47b7-8655-117c71feda8b

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

**Comment by Anjaliavv51** [comment]
@Amancoder-01 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Durgesh4993 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Amancoder-01 please assign me this issue

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me

**Comment by Anjaliavv51** [comment]
@Durgesh4993 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Amancoder-01  please assign me this issue
