### ISSUE TITLE
[New game]: Add quantum maze game

### ISSUE THREAD

**Issue by Aditi22Bansal** [ChromeGaming/GameSphere#1048]
### 🎮 Game Request

Game logic and basic description
"Quantum Maze" that involves navigating through a maze with quantum mechanics principles, including superposition and entanglement.

### Point down the features

Game points
Quantum Walls: Walls that can exist in multiple states simultaneously. Players must collapse these walls by observing them to determine if they are passable.
Entangled Paths: Certain paths are entangled, meaning if you choose one path, the corresponding entangled path changes as well.
Superposition Gates: Gates that require the player to be in two places at once, achieved by splitting the player's state.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

**Comment by Aditi22Bansal** [comment]
@Amancoder-01 
Kindly assign me this issue

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
@Amancoder-01 
I have created the PR
Kindly assign, review, merge and assign suitable labels

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review and merge

**Comment by honey7733** [comment]
I would like to work on this project or issue. Kindly assign it to me.
