### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by Tisha6661** [ChromeGaming/GameSphere#391]
### 🎮 Game Request

Flappy Bird is an arcade-style game in which the player controls the bird, which moves persistently to the right. The player is tasked with navigating bird through pairs of pipes that have equally sized gaps placed at random heights.

### Point down the features

Simple Gameplay: Tap or click to make the bird fly and navigate through obstacles.
Obstacle Avoidance: Maneuver the bird through gaps in pipes without touching them.
Scoring System: Keep track of the number of pipes passed to increase the score.
Flappy Physics: Experience gravity affecting the bird's flight as it gradually descends.
Challenging Difficulty: Navigate through narrow gaps with precise timing.
Endless Gameplay: Play indefinitely until hitting a pipe.
High Score Tracking: Track and compete for the best score achieved.
Simple Visuals: Enjoy minimalist 2D graphics with a side-scrolling view.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Durgesh4993** [comment]
@Tisha6661 This game is also exist
