### ISSUE TITLE
[New game]: 

### ISSUE THREAD

**Issue by SoarinSkySagar** [ChromeGaming/GameSphere#477]
### 🎮 Game Request

Game logic and basic description
A pokemon game to play with action packed fights and wild pokemon. Gotta catch 'em all!

### Point down the features

Game points
Interactive, Responsive site, fun to play

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by SoarinSkySagar** [comment]
@Aman1-coder @Durgesh4993 please assign me this issue

**Comment by Durgesh4993** [comment]
@SoarinSkySagar Please add a demo vedio
