### ISSUE TITLE
[Game]:  Earth Guardian

### ISSUE THREAD

**Issue by Pujan-sarkar** [ChromeGaming/GameSphere#943]
## Game Name 
 Earth Guardian

## Description

Earth Guardian is a remake of the classic Space shooter type of games, with 8-bit (pixel art) assets. This project used free assets (music and graphics) provided by [Jonathan So](https://jonathan-so.itch.io/),[KennyNL](https://kenney.nl/) and other sources, like Google images and [OpenGameArt](https://opengameart.org). This was a learning project. There will be some updates in the near future. Hope you like it, have fun!

## Screenshot Section

![Earth Guardian](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/144250917/f49f53d3-0fe5-46c5-b755-65c447bf67fc)

### Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### Thank you for raising issue in GameSpher 3.0

I want to add my game Earth Guardian game in your website under GSSoC'24 , so please can you assign it to me .

**Comment by Pujan-sarkar** [comment]
@Durgesh4993  please assign this issue to me and add gssoc and level tag please

**Comment by Pujan-sarkar** [comment]
@Durgesh4993  can you assign this issue to me Or please give some reply

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 as I added a new game can you change the label from level 2 to level 3 please sir .....

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 please merge the pr
