### ISSUE TITLE
[Game]:  want to add Baseball_Game

### ISSUE THREAD

**Issue by pallasivasai** [ChromeGaming/GameSphere#957]
## Description

this is Baseball game which is so interesting to play fully depends on js!

## Screenshot Section

in the PR I will upload the screen shot and video as well!

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by pallasivasai** [comment]
please review my prs at onces @Durgesh4993  #959 #956 #955
