### ISSUE TITLE
[Game]: want to add Ball_Fall_Game

### ISSUE THREAD

**Issue by pallasivasai** [ChromeGaming/GameSphere#958]
## Description

this an ball fall game which is very funny and interesting game as well!

## Screenshot Section

![Ball Fall - Google Chrome 17-05-2024 10_32_13](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/56314427/64c931f0-c13b-41c1-8f9f-a667f27d333a)

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Varshajha5** [comment]
@Durgesh4993 please assign this issue to me under gssoc 2024
