### ISSUE TITLE
[Game]: Flappy Bird

### ISSUE THREAD

**Issue by isha-dutta** [ChromeGaming/GameSphere#965]
## Description

In this single-player competitive game, the player controls a bird that must navigate between obstacles by understanding and manipulating gravity. Successfully passing through each obstacle earns the player one point.
The feature is considered complete when the bird can consistently navigate through the obstacles without touching them or flying too high or too low, which would otherwise end the game. Each successful passage through an obstacle awards the player one point on the scoreboard.

## Screenshot Section

<img width="905" alt="image" src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/134736220/7edf0007-d9b4-4de0-9c1d-321e614f1918">
<img width="901" alt="image" src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/134736220/0562b15e-a497-40ca-a070-0ad0495e4a18">

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Varshajha5** [comment]
@Durgesh4993 PLEASE ASSIGN THIS ISSUE TO ME UNDER gssoc 2024
