### ISSUE TITLE
[Game]: want to add a Bash_Mole_Game

### ISSUE THREAD

**Issue by pallasivasai** [ChromeGaming/GameSphere#966]
## Description

we just have to choose the dog inside the box per choosing only points will increase 
time limit is 60sec only

## Screenshot Section

On way!

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
@pallasivasai Please complete all tasks, then i'll assign you new issues

**Comment by Yuvraj960** [comment]
@Durgesh4993 Please assign this issue to me under GSSoC24
