### ISSUE TITLE
[Game]: Cooking_Challenge Game

### ISSUE THREAD

**Issue by pallasivasai** [ChromeGaming/GameSphere#968]
## Description

it will ask for ingredients any wrong pick all points loos and it will say wrong serve!
Correct combination of food items will add 10 marks
no negative marks
time limit will be 60 sec

## Screenshot Section

on way!

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
@pallasivasai Please complete all tasks, then i'll assign you new issues
