### ISSUE TITLE
[Game]: Duck Hunt Game

### ISSUE THREAD

**Issue by pallasivasai** [ChromeGaming/GameSphere#971]
## Description

Duck Hunt Game 

## Screenshot Section

on way!

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
@pallasivasai Please complete all tasks, then i'll assign you new issues
