### ISSUE TITLE
[Game]: Flames Game

### ISSUE THREAD

**Issue by Damini2004** [ChromeGaming/GameSphere#981]
## Game Name
Flames Game using Javascript
## Description

The Flames game is a popular game that determines the relationship between two people based on their names. The acronym "FLAMES" stands for Friends, Lovers, Affectionate, Marriage, Enemies, and Siblings. 

## Screenshot Section
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119414762/d78c003b-1acf-4537-a952-87db06887687)

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### Thank you for raising issue in GameSpher 3.0
Kindly assign this issue to me under GSSOC24

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Damini2004** [comment]
@Durgesh4993 Pull request has been created
